name: Construir y Subir Imagen FRONTEND

on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  build-and-push-vectorizer:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write 

    steps:
      - name: 📥 Descargar el código
        uses: actions/checkout@v3

      # -----------------------------------------------------------
      # MAGIA MULTI-ARQUITECTURA (ARM e INTEL)
      # -----------------------------------------------------------
      - name: ⚙️ Configurar QEMU
        uses: docker/setup-qemu-action@v2

      - name: 🛠️ Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      # -----------------------------------------------------------
      # LOGIN
      # -----------------------------------------------------------
      - name: 🔑 Iniciar sesión en el Registro de GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: 🔠 Convertir el nombre del repositorio a minúsculas
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # -----------------------------------------------------------
      # CONSTRUIR IMAGEN 2: FRONTEND
      # -----------------------------------------------------------
      - name: 🛡️ Construir y Subir FRONTEND
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.REPO }}-frontend:latest
